# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

APP_IDENTIFIER="com.carrefour.carrefourPass"
APPLE_ID="alvaro.nieto.cuesta@carrefour.com"
TEAM_ID="24M2Y5UE44"
WORKSPACE="sfc-leonardo.xcworkspace"

platform :ios do

  desc "Runs specs"
  lane :specs do
    scan(
      project:'InternalPoCSFC.xcodeproj',
      scheme:'InternalPoCSFCTests',
      device: 'iPhone 8',
      output_files: 'InternalPoCSFC.junit',
      buildlog_path: './fastlane/fastlane-buildlog',
      derived_data_path: '~/Library/Developer/Xcode/DerivedData',
      result_bundle: true
    )
  end

  desc "Build the IPA"
  lane :build_ipa do
    buildNumber = increment_build_number
    if ENV["CUA"] == "true"
      otherSwiftFlags = otherSwiftFlags + "-DCUA"
    end

    xcargs = otherSwiftFlags
    gym(
      project: "InternalPoCSFC.xcodeproj",
      scheme: "InternalPoCSFC",
      configuration: "PRO",
      output_name: "InternalPoCSFC.ipa",
      export_method: "app-store",
      include_bitcode: false,
      clean: false,
      xcargs: xcargs
    )
    appIdentifier = "com.icologic.InternalPoCSFC"
    add_git_tag(
      grouping: "fastlane-builds",
      includes_lane: true,
      prefix: "v",
      postfix: "-RC",
      build_number: buildNumber
    )
  end

  desc "Description of what the lane does release"
  lane :release do
    increment_build_number                # automatically increment by one
    capture_screenshots                   # generate new screenshots for the App Store
    sync_code_signing(type: "appstore")   # see code signing guide for more information
    build_app(scheme: 'sfc-leonardo-PRO',
              workspace: 'sfc-leonardo.xcworkspace',
              include_bitcode: true)
    upload_to_app_store
  end

  upload_to_testflight(
    username: "felix@krausefx.com",
    app_identifier: "com.krausefx.app",
    itc_provider: "abcde12345" # pass a specific value to the iTMSTransporter -itc_provider option
  )

  upload_to_testflight(
    beta_app_feedback_email: "email@email.com",
    beta_app_description: "This is a description of my app",
    demo_account_required: true,
    notify_external_testers: false,
    changelog: "This is my changelog of things that have changed in a log"
  )

  upload_to_testflight(
    beta_app_review_info: {
    contact_email: "email@email.com",
    contact_first_name: "Connect",
    contact_last_name: "API",
    contact_phone: "5558675309",
    demo_account_name: "demo@email.com",
    demo_account_password: "connectapi",
    notes: "this is review note for the reviewer <3 thank you for reviewing"
    },
  localized_app_info: {
    "default": {
      feedback_email: "default@email.com",
      marketing_url: "https://example.com/marketing-defafult",
      privacy_policy_url: "https://example.com/privacy-defafult",
      description: "Default description",
    },
    "en-GB": {
      feedback_email: "en-gb@email.com",
      marketing_url: "https://example.com/marketing-en-gb",
      privacy_policy_url: "https://example.com/privacy-en-gb",
      description: "en-gb description",
    }
  },
  localized_build_info: {
    "default": {
      whats_new: "Default changelog",
    },
    "en-GB": {
      whats_new: "en-gb changelog",
    }
  }
)

 lane :appcenter_release do
  desc "Description of what the lane does appcenter_release"
  increment_build_number
  appcenter_upload(
    api_token: '193312cd04800ddec9a9de59846a63ec3a2026bf',
    owner_name: 'icologic',
    owner_type: 'organization',
    app_os: 'ios',
    app_name: "InternalPoCSFC",
    file: './InternalPoCSFC.ipa',
    notify_testers: true
  )
  clean_build_artifacts
 end

end
