# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

APP_IDENTIFIER="com.carrefour.carrefourPass"
APPLE_ID="alvaro.nieto.cuesta@carrefour.com"
TEAM_ID="24M2Y5UE44"
WORKSPACE="sfc-leonardo.xcworkspace"

platform :ios do

  desc "Runs specs"
  lane :specs do
    scan(
      project:'InternalPoCSFC.xcodeproj',
      scheme:'InternalPoCSFCTests',
      device: 'iPhone 8 (14.2)',
      output_files: 'InternalPoCSFC.junit'
    )
  end

  desc "Description of what the lane does release"
  lane :release do
    increment_build_number                # automatically increment by one
    capture_screenshots                   # generate new screenshots for the App Store
    sync_code_signing(type: "appstore")   # see code signing guide for more information
    build_app(scheme: 'sfc-leonardo-PRO',
              workspace: 'sfc-leonardo.xcworkspace',
              include_bitcode: true)
    upload_to_app_store
  end

  lane :betaTestFlight do
    desc "Description of what the lane does betaTestFlight"
    build_app(scheme: 'InternalPoCSFC',
              project: 'InternalPoCSFC.xcodeproj',
              include_bitcode: false)
    upload_to_testflight
  end

 lane :appcenter_release do
  desc "Description of what the lane does appcenter_release"
  increment_build_number
  appcenter_upload(
    api_token: '193312cd04800ddec9a9de59846a63ec3a2026bf',
    owner_name: 'icologic',
    owner_type: 'organization',
    app_os: 'ios',
    app_name: "InternalPoCSFC",
    file: './InternalPoCSFC.ipa',
    notify_testers: true
  )
  clean_build_artifacts
 end

end

platform :android do

  lane :playstore do
    gradle(task: 'assemble', build_type: 'Release')
    upload_to_play_store
  end

  lane :beta do
    # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup
    gradle(task: 'assemble', build_type: 'Release')
    upload_to_play_store(track: 'beta')

    # ...
  end

  lane :appcenter_release do
   desc "Description of what the lane does appcenter_release"
   increment_build_number
   appcenter_upload(
    api_token: '193312cd04800ddec9a9de59846a63ec3a2026bf',
    owner_name: 'icologic',
    owner_type: 'organization',
    app_os: 'Android',
    app_name: "InternalPoCSFC",
    file: './builds/InternalPoCSFC.apk',
    notify_testers: true
   )
   clean_build_artifacts
  end

end
